name: Install Rust

inputs:
  toolchain:
    description: The Rust toolchain to install
    required: true
    default: "stable"
  components:
    description: A comma-separated list of Rust components to install
    required: true
    default: "rustfmt,clippy"

outputs:
  cachekey:
    description: The hash of the installed rustc
    value: ${{ steps.rust.outputs.cachekey }}
  toolchain:
    description: The name of the installed toolchain
    value: ${{ steps.rust.outputs.name }}

runs:
  using: "composite"
  steps:
    - name: Install Rust
      id: rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ inputs.toolchain }}
        components: ${{ inputs.components }}

    - name: Add Cargo bin to Path
      run: |
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      shell: bash

    - name: Verify Rust install
      run: |
        echo "Verifying rust '${{ inputs.toolchain }}' ..."
        rustc --version
        cargo --version
        if [ "${{ contains(inputs.components, 'rustfmt') }}" == "true" ]; then
          rustfmt --version
        fi
        if [ "${{ contains(inputs.components, 'clippy') }}" == "true" ]; then
          cargo clippy --version
        fi
      shell: bash

    - name: Share rustc hash
      run: |
        echo 'RUSTC_HASH=${{ steps.rust.outputs.cachekey }}' >> $GITHUB_ENV
      shell: bash
