name: Filter matrix

inputs:
  matrix:
    description: A JSON array of names
    required: true
  changes:
    description: A JSON array of changed filters from "dorny/paths-filter"
    required: true
  prefix:
    description: A prefix to prepend to the name when searching for filters
    required: true
    default: ""
  suffix:
    description: A suffix to append to the name when searching for filters
    required: true
    default: ""

outputs:
  matrix:
    description: A JSON array of name that have changed
    value: ${{ steps.filter.outputs.matrix }}

runs:
  using: "composite"
  steps:
    - name: Filter matrix
      id: filter
      env:
        ORIGINAL: ${{ inputs.matrix }}
      run: |
        echo "original matrix = $ORIGINAL"
        ORIGINAL_KEYS=$(echo $ORIGINAL | jq -c '.[]' | sed 's/"//g')

        echo "changes = ${{ toJSON(inputs.changes) }}"
        CHANGES=$(echo ${{ toJSON(inputs.changes) }} | sed 's/-/_/g')
        CHANGED_KEYS=$(for key in $ORIGINAL_KEYS; do
          change_key=$(echo $key | sed 's/^/${{ inputs.prefix }}/' | sed 's/$/${{ inputs.suffix }}/' | sed 's/-/_/g')
          index=$(echo $CHANGES | jq -c ". | index(\"$change_key\")")
          if [ $(echo $index) != 'null' ]; then
            echo $key
          fi
        done)

        FILTERED_MATRIX=$(echo "$CHANGED_KEYS" | jq -R . | jq -sc . | sed 's/""//')
        echo "filtered matrix = $FILTERED_MATRIX"
        echo "matrix=$FILTERED_MATRIX" >> $GITHUB_OUTPUT
      shell: bash
